_target_: src.models.resnet_module_ventricular_rate.ResNetVentricularRate

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

num_classes: 300
lr: 1e-3
weight_decay: 2e-4
max_epochs: 100
