_target_: src.datamodules.br_datamodule.BRDataModule
data_dir: ${paths.data_dir}
batch_size: 50
total_images: 80,000
train_val_test_split: [63_000, 6_000, 11_000]
num_workers: 0
pin_memory: False
#data_path: '/mnt/qnap/idanlevy/data/brazilian/clean_images/'
data_path: '/Users/idanlevy/Documents/medpic/brazilian database/data/'
classification_category: 'AF'